[versions]

kotlin = "1.6.10"

# UI Tools
accompanist = "0.24.0-alpha"
coil = "1.4.0"
epoxy = "4.6.4"
groupie = "2.10.0"
insetter = "0.6.1"
material = "1.5.0"
material-compose-themeAdapter = "1.1.3"
material-compose-themeAdapter3 = "1.0.3"

# Multithreading
kotlinx-coroutines = "1.6.0"
reactivex-rxjava2 = "2.2.21"
reactivex-rxjava3 = "3.1.3"

# Network & Serialization
kotlinx-serialization = "1.3.2"
moshi = "1.13.0"
okhttp = "4.9.3"
retrofit = "2.9.0"
retrofit-converter-kotlinxSerialization = "0.8.0"

# Security
tink = "1.6.1"

# DI
dagger = "2.40.5"

# Test
junit = "5.8.2"
junit4 = "4.13"
kotest = "5.1.0"
mockk = "1.12.2"

# Debug Tools
leakcanary = "2.8.1"
timber = "5.0.1"

# Annotations procesing
ksp = "1.6.10-1.0.2"

# Services
firebase-analytics = "20.0.2"
firebase-bom = "29.0.3"
firebase-crashlytics = "18.2.6"
firebase-messaging = "23.0.0"

[libraries]

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

# UI Tools
accompanist-appcompatTheme = { module = "com.google.accompanist:accompanist-appcompat-theme", version.ref = "accompanist" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
epoxy = { module = "com.airbnb.android:epoxy", version.ref = "epoxy" }
epoxy-paging3 = { module = "com.airbnb.android:epoxy-paging3", version.ref = "epoxy" }
epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxy" }
groupie = { module = "com.github.lisawray.groupie:groupie", version.ref = "groupie" }
insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-compose-themeAdapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "material-compose-themeAdapter" }
material-compose-themeAdapter3 = { module = "com.google.android.material:compose-theme-adapter-3", version.ref = "material-compose-themeAdapter3" }

# Multithreading
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "reactivex-rxjava2" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "reactivex-rxjava3" }

# Network & Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver3 = { module = "com.squareup.okhttp3:mockwebserver3", version.ref = "okhttp" }
okhttp-mockwebserver3-junit4 = { module = "com.squareup.okhttp3:mockwebserver3-junit4", version.ref = "okhttp" }
okhttp-mockwebserver3-junit5 = { module = "com.squareup.okhttp3:mockwebserver3-junit5", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinxSerialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-converter-kotlinxSerialization" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }

# Security
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tink" }

# DI
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

# Test
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", versoin.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", versoin.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", versoin.ref = "junit" }
junit-jupiter-migrationsupport = { module = "org.junit.jupiter:junit-jupiter-migrationsupport", versoin.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", versoin.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", versoin.ref = "junit" }
junit-platform-runner = { module = "org.junit.platform:junit-platform-runner", versoin.ref = "junit" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", versoin.ref = "junit" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# Debug Tools
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Annotations procesing
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# Services
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebase-messaging" }
