[versions]

# Ui Tools
airbnb-epoxy = "4.6.2"
insetter = "0.6.6"
coil-kt = "1.3.2"
material = "1.4.0"
groupie = "2.9.0"

# Multithreading
kotlinx-coroutines = "1.5.1"
reactivex-rxjava2 = "2.2.21"
reactivex-rxjava3 = "3.1.0"

# Network
timber = "5.0.1"
moshi = "1.12.0"
okhttp = "4.9.1"
retrofit2-converter-moshi = "2.9.0"
retrofit2-retrofit = "2.9.0"

# DI
google-dagger = "2.38.1"

# Test
kotest = "4.6.1"
kotlinx-serialization-json = "1.2.2"
mockk = "1.12.0"

# Debug Tools
leakcanary = "2.7"

[libraries]

# UI Tools
airbnb-epoxy = { module = "com.airbnb.android:epoxy", version.ref = "airbnb-epoxy" }
airbnb-epoxy-paging3 = { module = "com.airbnb.android:epoxy-paging3", version.ref = "airbnb-epoxy" }
airbnb-epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "airbnb-epoxy" }
insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
coil = { module = "io.coil-kt:coil", version.ref = "coil-kt" }
material = { module = "com.google.android.material:material", version.ref = "material" }
groupie = { module = "com.github.lisawray.groupie:groupie", version.ref = "groupie" }

# Multithreading
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "reactivex-rxjava2" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "reactivex-rxjava3" }

# Network
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp-interceptor-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2-retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit2-converter-moshi" }

# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# DI
dagger = { module = "com.google.dagger:dagger", version.ref = "google-dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "google-dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "google-dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "google-dagger" }

# Test
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# Debug Tools
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
