[versions]

# Ui Tools
coil = "1.4.0"
epoxy = "4.6.4"
groupie = "2.10.0"
insetter = "0.6.1"
material = "1.5.0"

# Multithreading
kotlinx-coroutines = "1.6.0"
reactivex-rxjava2 = "2.2.21"
reactivex-rxjava3 = "3.1.3"

# Network
okhttp = "4.9.3"
retrofit2 = "2.9.0"

# Serialization
kotlinx-serialization = "1.3.2"
moshi = "1.13.0"

# DI
google-dagger = "2.40.5"

# Test
kotest = "5.1.0"
mockk = "1.12.2"

# Debug Tools
leakcanary = "2.8.1"
timber = "5.0.1"

# Annotations procesing
ksp = "1.6.10-1.0.2"

[libraries]

# UI Tools
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
epoxy = { module = "com.airbnb.android:epoxy", version.ref = "epoxy" }
epoxy-paging3 = { module = "com.airbnb.android:epoxy-paging3", version.ref = "epoxy" }
epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxy" }
groupie = { module = "com.github.lisawray.groupie:groupie", version.ref = "groupie" }
insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
material = { module = "com.google.android.material:material", version.ref = "material" }

# Multithreading
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "reactivex-rxjava2" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "reactivex-rxjava3" }

# Network
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit2" }

# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

# DI
dagger = { module = "com.google.dagger:dagger", version.ref = "google-dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "google-dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "google-dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "google-dagger" }

# Test
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# Debug Tools
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Annotations procesing
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
